//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BackwardsLua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BackwardsLuaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IBackwardsLuaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsCompletionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsCompletionExpr([NotNull] BackwardsLuaParser.BackwardsCompletionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminal([NotNull] BackwardsLuaParser.TerminalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsPartialCompletion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsPartialCompletion([NotNull] BackwardsLuaParser.BackwardsPartialCompletionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsStartSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsStartSymbol([NotNull] BackwardsLuaParser.BackwardsStartSymbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.completionChain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompletionChain([NotNull] BackwardsLuaParser.CompletionChainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSegment([NotNull] BackwardsLuaParser.SegmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.anonymousPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymousPart([NotNull] BackwardsLuaParser.AnonymousPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsField([NotNull] BackwardsLuaParser.BackwardsFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsAnonCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsAnonCall([NotNull] BackwardsLuaParser.BackwardsAnonCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsAnonArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsAnonArray([NotNull] BackwardsLuaParser.BackwardsAnonArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsCall([NotNull] BackwardsLuaParser.BackwardsCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.backwardsArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackwardsArgs([NotNull] BackwardsLuaParser.BackwardsArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] BackwardsLuaParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BackwardsLuaParser.ignoredExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIgnoredExpr([NotNull] BackwardsLuaParser.IgnoredExprContext context);
}
