//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IncompleteLua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IncompleteLuaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IIncompleteLuaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChunk([NotNull] IncompleteLuaParser.ChunkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChunk([NotNull] IncompleteLuaParser.ChunkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteChunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteChunk([NotNull] IncompleteLuaParser.IncompleteChunkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteChunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteChunk([NotNull] IncompleteLuaParser.IncompleteChunkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] IncompleteLuaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] IncompleteLuaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteBlock([NotNull] IncompleteLuaParser.IncompleteBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteBlock([NotNull] IncompleteLuaParser.IncompleteBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] IncompleteLuaParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] IncompleteLuaParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteStat([NotNull] IncompleteLuaParser.IncompleteStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteStat([NotNull] IncompleteLuaParser.IncompleteStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteElse([NotNull] IncompleteLuaParser.IncompleteElseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteElse([NotNull] IncompleteLuaParser.IncompleteElseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetstat([NotNull] IncompleteLuaParser.RetstatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetstat([NotNull] IncompleteLuaParser.RetstatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteRetstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteRetstat([NotNull] IncompleteLuaParser.IncompleteRetstatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteRetstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteRetstat([NotNull] IncompleteLuaParser.IncompleteRetstatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] IncompleteLuaParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] IncompleteLuaParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncname([NotNull] IncompleteLuaParser.FuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncname([NotNull] IncompleteLuaParser.FuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteFuncname([NotNull] IncompleteLuaParser.IncompleteFuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteFuncname([NotNull] IncompleteLuaParser.IncompleteFuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarlist([NotNull] IncompleteLuaParser.VarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarlist([NotNull] IncompleteLuaParser.VarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteVarlist([NotNull] IncompleteLuaParser.IncompleteVarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteVarlist([NotNull] IncompleteLuaParser.IncompleteVarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamelist([NotNull] IncompleteLuaParser.NamelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamelist([NotNull] IncompleteLuaParser.NamelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteNamelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteNamelist([NotNull] IncompleteLuaParser.IncompleteNamelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteNamelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteNamelist([NotNull] IncompleteLuaParser.IncompleteNamelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplist([NotNull] IncompleteLuaParser.ExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplist([NotNull] IncompleteLuaParser.ExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteExplist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteExplist([NotNull] IncompleteLuaParser.IncompleteExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteExplist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteExplist([NotNull] IncompleteLuaParser.IncompleteExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] IncompleteLuaParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] IncompleteLuaParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteExp([NotNull] IncompleteLuaParser.IncompleteExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteExp([NotNull] IncompleteLuaParser.IncompleteExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixexp([NotNull] IncompleteLuaParser.PrefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixexp([NotNull] IncompleteLuaParser.PrefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompletePrefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompletePrefixexp([NotNull] IncompleteLuaParser.IncompletePrefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompletePrefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompletePrefixexp([NotNull] IncompleteLuaParser.IncompletePrefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctioncall([NotNull] IncompleteLuaParser.FunctioncallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctioncall([NotNull] IncompleteLuaParser.FunctioncallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteFunctionCall([NotNull] IncompleteLuaParser.IncompleteFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteFunctionCall([NotNull] IncompleteLuaParser.IncompleteFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrExp([NotNull] IncompleteLuaParser.VarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrExp([NotNull] IncompleteLuaParser.VarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteVarOrExp([NotNull] IncompleteLuaParser.IncompleteVarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteVarOrExp([NotNull] IncompleteLuaParser.IncompleteVarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarName([NotNull] IncompleteLuaParser.VarNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarName([NotNull] IncompleteLuaParser.VarNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] IncompleteLuaParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] IncompleteLuaParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteVar([NotNull] IncompleteLuaParser.IncompleteVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteVar([NotNull] IncompleteLuaParser.IncompleteVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarSuffix([NotNull] IncompleteLuaParser.VarSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarSuffix([NotNull] IncompleteLuaParser.VarSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteVarSuffix([NotNull] IncompleteLuaParser.IncompleteVarSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteVarSuffix([NotNull] IncompleteLuaParser.IncompleteVarSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameAndArgs([NotNull] IncompleteLuaParser.NameAndArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameAndArgs([NotNull] IncompleteLuaParser.NameAndArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteNameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteNameAndArgs([NotNull] IncompleteLuaParser.IncompleteNameAndArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteNameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteNameAndArgs([NotNull] IncompleteLuaParser.IncompleteNameAndArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] IncompleteLuaParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] IncompleteLuaParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteArgs([NotNull] IncompleteLuaParser.IncompleteArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteArgs([NotNull] IncompleteLuaParser.IncompleteArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctiondef([NotNull] IncompleteLuaParser.FunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctiondef([NotNull] IncompleteLuaParser.FunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteFunctiondef([NotNull] IncompleteLuaParser.IncompleteFunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteFunctiondef([NotNull] IncompleteLuaParser.IncompleteFunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncbody([NotNull] IncompleteLuaParser.FuncbodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncbody([NotNull] IncompleteLuaParser.FuncbodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteFuncbody([NotNull] IncompleteLuaParser.IncompleteFuncbodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteFuncbody([NotNull] IncompleteLuaParser.IncompleteFuncbodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParlist([NotNull] IncompleteLuaParser.ParlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParlist([NotNull] IncompleteLuaParser.ParlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteParlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteParlist([NotNull] IncompleteLuaParser.IncompleteParlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteParlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteParlist([NotNull] IncompleteLuaParser.IncompleteParlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableconstructor([NotNull] IncompleteLuaParser.TableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableconstructor([NotNull] IncompleteLuaParser.TableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteTableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteTableconstructor([NotNull] IncompleteLuaParser.IncompleteTableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteTableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteTableconstructor([NotNull] IncompleteLuaParser.IncompleteTableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldlist([NotNull] IncompleteLuaParser.FieldlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldlist([NotNull] IncompleteLuaParser.FieldlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteFieldlist([NotNull] IncompleteLuaParser.IncompleteFieldlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteFieldlist([NotNull] IncompleteLuaParser.IncompleteFieldlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] IncompleteLuaParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] IncompleteLuaParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteField([NotNull] IncompleteLuaParser.IncompleteFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteField([NotNull] IncompleteLuaParser.IncompleteFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldsep([NotNull] IncompleteLuaParser.FieldsepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldsep([NotNull] IncompleteLuaParser.FieldsepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorOr([NotNull] IncompleteLuaParser.OperatorOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorOr([NotNull] IncompleteLuaParser.OperatorOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAnd([NotNull] IncompleteLuaParser.OperatorAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAnd([NotNull] IncompleteLuaParser.OperatorAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorComparison([NotNull] IncompleteLuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorComparison([NotNull] IncompleteLuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorStrcat([NotNull] IncompleteLuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorStrcat([NotNull] IncompleteLuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAddSub([NotNull] IncompleteLuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAddSub([NotNull] IncompleteLuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorMulDivMod([NotNull] IncompleteLuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorMulDivMod([NotNull] IncompleteLuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorBitwise([NotNull] IncompleteLuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorBitwise([NotNull] IncompleteLuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorUnary([NotNull] IncompleteLuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorUnary([NotNull] IncompleteLuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorPower([NotNull] IncompleteLuaParser.OperatorPowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorPower([NotNull] IncompleteLuaParser.OperatorPowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] IncompleteLuaParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] IncompleteLuaParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] IncompleteLuaParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] IncompleteLuaParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteString([NotNull] IncompleteLuaParser.IncompleteStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteString([NotNull] IncompleteLuaParser.IncompleteStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncompleteName([NotNull] IncompleteLuaParser.IncompleteNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncompleteName([NotNull] IncompleteLuaParser.IncompleteNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] IncompleteLuaParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] IncompleteLuaParser.KeywordContext context);
}
