//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IncompleteLua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="IncompleteLuaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IIncompleteLuaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChunk([NotNull] IncompleteLuaParser.ChunkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteChunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteChunk([NotNull] IncompleteLuaParser.IncompleteChunkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] IncompleteLuaParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteBlock([NotNull] IncompleteLuaParser.IncompleteBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat([NotNull] IncompleteLuaParser.StatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteStat([NotNull] IncompleteLuaParser.IncompleteStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteElse([NotNull] IncompleteLuaParser.IncompleteElseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetstat([NotNull] IncompleteLuaParser.RetstatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteRetstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteRetstat([NotNull] IncompleteLuaParser.IncompleteRetstatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] IncompleteLuaParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncname([NotNull] IncompleteLuaParser.FuncnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteFuncname([NotNull] IncompleteLuaParser.IncompleteFuncnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarlist([NotNull] IncompleteLuaParser.VarlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteVarlist([NotNull] IncompleteLuaParser.IncompleteVarlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamelist([NotNull] IncompleteLuaParser.NamelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteNamelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteNamelist([NotNull] IncompleteLuaParser.IncompleteNamelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplist([NotNull] IncompleteLuaParser.ExplistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteExplist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteExplist([NotNull] IncompleteLuaParser.IncompleteExplistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp([NotNull] IncompleteLuaParser.ExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteExp([NotNull] IncompleteLuaParser.IncompleteExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixexp([NotNull] IncompleteLuaParser.PrefixexpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompletePrefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompletePrefixexp([NotNull] IncompleteLuaParser.IncompletePrefixexpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctioncall([NotNull] IncompleteLuaParser.FunctioncallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteFunctionCall([NotNull] IncompleteLuaParser.IncompleteFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarOrExp([NotNull] IncompleteLuaParser.VarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteVarOrExp([NotNull] IncompleteLuaParser.IncompleteVarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] IncompleteLuaParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteVar([NotNull] IncompleteLuaParser.IncompleteVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarSuffix([NotNull] IncompleteLuaParser.VarSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteVarSuffix([NotNull] IncompleteLuaParser.IncompleteVarSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameAndArgs([NotNull] IncompleteLuaParser.NameAndArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteNameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteNameAndArgs([NotNull] IncompleteLuaParser.IncompleteNameAndArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] IncompleteLuaParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteArgs([NotNull] IncompleteLuaParser.IncompleteArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiondef([NotNull] IncompleteLuaParser.FunctiondefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteFunctiondef([NotNull] IncompleteLuaParser.IncompleteFunctiondefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncbody([NotNull] IncompleteLuaParser.FuncbodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteFuncbody([NotNull] IncompleteLuaParser.IncompleteFuncbodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParlist([NotNull] IncompleteLuaParser.ParlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteParlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteParlist([NotNull] IncompleteLuaParser.IncompleteParlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableconstructor([NotNull] IncompleteLuaParser.TableconstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteTableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteTableconstructor([NotNull] IncompleteLuaParser.IncompleteTableconstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldlist([NotNull] IncompleteLuaParser.FieldlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteFieldlist([NotNull] IncompleteLuaParser.IncompleteFieldlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] IncompleteLuaParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteField([NotNull] IncompleteLuaParser.IncompleteFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldsep([NotNull] IncompleteLuaParser.FieldsepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorOr([NotNull] IncompleteLuaParser.OperatorOrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorAnd([NotNull] IncompleteLuaParser.OperatorAndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorComparison([NotNull] IncompleteLuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorStrcat([NotNull] IncompleteLuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorAddSub([NotNull] IncompleteLuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorMulDivMod([NotNull] IncompleteLuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorBitwise([NotNull] IncompleteLuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorUnary([NotNull] IncompleteLuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorPower([NotNull] IncompleteLuaParser.OperatorPowerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] IncompleteLuaParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] IncompleteLuaParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteString([NotNull] IncompleteLuaParser.IncompleteStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IncompleteLuaParser.incompleteName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncompleteName([NotNull] IncompleteLuaParser.IncompleteNameContext context);
}
