//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IncompleteLua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IIncompleteLuaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class IncompleteLuaBaseListener : IIncompleteLuaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChunk([NotNull] IncompleteLuaParser.ChunkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChunk([NotNull] IncompleteLuaParser.ChunkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteChunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteChunk([NotNull] IncompleteLuaParser.IncompleteChunkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteChunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteChunk([NotNull] IncompleteLuaParser.IncompleteChunkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] IncompleteLuaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] IncompleteLuaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteBlock([NotNull] IncompleteLuaParser.IncompleteBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteBlock([NotNull] IncompleteLuaParser.IncompleteBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] IncompleteLuaParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] IncompleteLuaParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteStat([NotNull] IncompleteLuaParser.IncompleteStatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteStat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteStat([NotNull] IncompleteLuaParser.IncompleteStatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteElse([NotNull] IncompleteLuaParser.IncompleteElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteElse([NotNull] IncompleteLuaParser.IncompleteElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetstat([NotNull] IncompleteLuaParser.RetstatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetstat([NotNull] IncompleteLuaParser.RetstatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteRetstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteRetstat([NotNull] IncompleteLuaParser.IncompleteRetstatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteRetstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteRetstat([NotNull] IncompleteLuaParser.IncompleteRetstatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] IncompleteLuaParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] IncompleteLuaParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncname([NotNull] IncompleteLuaParser.FuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncname([NotNull] IncompleteLuaParser.FuncnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteFuncname([NotNull] IncompleteLuaParser.IncompleteFuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteFuncname([NotNull] IncompleteLuaParser.IncompleteFuncnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarlist([NotNull] IncompleteLuaParser.VarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarlist([NotNull] IncompleteLuaParser.VarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteVarlist([NotNull] IncompleteLuaParser.IncompleteVarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteVarlist([NotNull] IncompleteLuaParser.IncompleteVarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamelist([NotNull] IncompleteLuaParser.NamelistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamelist([NotNull] IncompleteLuaParser.NamelistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteNamelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteNamelist([NotNull] IncompleteLuaParser.IncompleteNamelistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteNamelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteNamelist([NotNull] IncompleteLuaParser.IncompleteNamelistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.explist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplist([NotNull] IncompleteLuaParser.ExplistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.explist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplist([NotNull] IncompleteLuaParser.ExplistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteExplist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteExplist([NotNull] IncompleteLuaParser.IncompleteExplistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteExplist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteExplist([NotNull] IncompleteLuaParser.IncompleteExplistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] IncompleteLuaParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] IncompleteLuaParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteExp([NotNull] IncompleteLuaParser.IncompleteExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteExp([NotNull] IncompleteLuaParser.IncompleteExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixexp([NotNull] IncompleteLuaParser.PrefixexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixexp([NotNull] IncompleteLuaParser.PrefixexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompletePrefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompletePrefixexp([NotNull] IncompleteLuaParser.IncompletePrefixexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompletePrefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompletePrefixexp([NotNull] IncompleteLuaParser.IncompletePrefixexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctioncall([NotNull] IncompleteLuaParser.FunctioncallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctioncall([NotNull] IncompleteLuaParser.FunctioncallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteFunctionCall([NotNull] IncompleteLuaParser.IncompleteFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteFunctionCall([NotNull] IncompleteLuaParser.IncompleteFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrExp([NotNull] IncompleteLuaParser.VarOrExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrExp([NotNull] IncompleteLuaParser.VarOrExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteVarOrExp([NotNull] IncompleteLuaParser.IncompleteVarOrExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteVarOrExp([NotNull] IncompleteLuaParser.IncompleteVarOrExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarName([NotNull] IncompleteLuaParser.VarNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarName([NotNull] IncompleteLuaParser.VarNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] IncompleteLuaParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] IncompleteLuaParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteVar([NotNull] IncompleteLuaParser.IncompleteVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteVar([NotNull] IncompleteLuaParser.IncompleteVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.varSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarSuffix([NotNull] IncompleteLuaParser.VarSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.varSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarSuffix([NotNull] IncompleteLuaParser.VarSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteVarSuffix([NotNull] IncompleteLuaParser.IncompleteVarSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteVarSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteVarSuffix([NotNull] IncompleteLuaParser.IncompleteVarSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.nameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameAndArgs([NotNull] IncompleteLuaParser.NameAndArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.nameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameAndArgs([NotNull] IncompleteLuaParser.NameAndArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteNameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteNameAndArgs([NotNull] IncompleteLuaParser.IncompleteNameAndArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteNameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteNameAndArgs([NotNull] IncompleteLuaParser.IncompleteNameAndArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] IncompleteLuaParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] IncompleteLuaParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteArgs([NotNull] IncompleteLuaParser.IncompleteArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteArgs([NotNull] IncompleteLuaParser.IncompleteArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctiondef([NotNull] IncompleteLuaParser.FunctiondefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctiondef([NotNull] IncompleteLuaParser.FunctiondefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteFunctiondef([NotNull] IncompleteLuaParser.IncompleteFunctiondefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFunctiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteFunctiondef([NotNull] IncompleteLuaParser.IncompleteFunctiondefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.funcbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncbody([NotNull] IncompleteLuaParser.FuncbodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.funcbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncbody([NotNull] IncompleteLuaParser.FuncbodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteFuncbody([NotNull] IncompleteLuaParser.IncompleteFuncbodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFuncbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteFuncbody([NotNull] IncompleteLuaParser.IncompleteFuncbodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParlist([NotNull] IncompleteLuaParser.ParlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParlist([NotNull] IncompleteLuaParser.ParlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteParlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteParlist([NotNull] IncompleteLuaParser.IncompleteParlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteParlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteParlist([NotNull] IncompleteLuaParser.IncompleteParlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableconstructor([NotNull] IncompleteLuaParser.TableconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableconstructor([NotNull] IncompleteLuaParser.TableconstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteTableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteTableconstructor([NotNull] IncompleteLuaParser.IncompleteTableconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteTableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteTableconstructor([NotNull] IncompleteLuaParser.IncompleteTableconstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.fieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldlist([NotNull] IncompleteLuaParser.FieldlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.fieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldlist([NotNull] IncompleteLuaParser.FieldlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteFieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteFieldlist([NotNull] IncompleteLuaParser.IncompleteFieldlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteFieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteFieldlist([NotNull] IncompleteLuaParser.IncompleteFieldlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] IncompleteLuaParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] IncompleteLuaParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteField([NotNull] IncompleteLuaParser.IncompleteFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteField([NotNull] IncompleteLuaParser.IncompleteFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsep([NotNull] IncompleteLuaParser.FieldsepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsep([NotNull] IncompleteLuaParser.FieldsepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOr([NotNull] IncompleteLuaParser.OperatorOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOr([NotNull] IncompleteLuaParser.OperatorOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAnd([NotNull] IncompleteLuaParser.OperatorAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAnd([NotNull] IncompleteLuaParser.OperatorAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorComparison([NotNull] IncompleteLuaParser.OperatorComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorComparison([NotNull] IncompleteLuaParser.OperatorComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorStrcat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorStrcat([NotNull] IncompleteLuaParser.OperatorStrcatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorStrcat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorStrcat([NotNull] IncompleteLuaParser.OperatorStrcatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAddSub([NotNull] IncompleteLuaParser.OperatorAddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAddSub([NotNull] IncompleteLuaParser.OperatorAddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorMulDivMod([NotNull] IncompleteLuaParser.OperatorMulDivModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorMulDivMod([NotNull] IncompleteLuaParser.OperatorMulDivModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorBitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorBitwise([NotNull] IncompleteLuaParser.OperatorBitwiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorBitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorBitwise([NotNull] IncompleteLuaParser.OperatorBitwiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorUnary([NotNull] IncompleteLuaParser.OperatorUnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorUnary([NotNull] IncompleteLuaParser.OperatorUnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.operatorPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorPower([NotNull] IncompleteLuaParser.OperatorPowerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.operatorPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorPower([NotNull] IncompleteLuaParser.OperatorPowerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] IncompleteLuaParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] IncompleteLuaParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] IncompleteLuaParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] IncompleteLuaParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteString([NotNull] IncompleteLuaParser.IncompleteStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteString([NotNull] IncompleteLuaParser.IncompleteStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IncompleteLuaParser.incompleteName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncompleteName([NotNull] IncompleteLuaParser.IncompleteNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IncompleteLuaParser.incompleteName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncompleteName([NotNull] IncompleteLuaParser.IncompleteNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
