//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LuaCompletion.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LuaCompletionParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ILuaCompletionListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChunk([NotNull] LuaCompletionParser.ChunkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChunk([NotNull] LuaCompletionParser.ChunkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LuaCompletionParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LuaCompletionParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] LuaCompletionParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] LuaCompletionParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetstat([NotNull] LuaCompletionParser.RetstatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetstat([NotNull] LuaCompletionParser.RetstatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] LuaCompletionParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] LuaCompletionParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncname([NotNull] LuaCompletionParser.FuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncname([NotNull] LuaCompletionParser.FuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarlist([NotNull] LuaCompletionParser.VarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarlist([NotNull] LuaCompletionParser.VarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamelist([NotNull] LuaCompletionParser.NamelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamelist([NotNull] LuaCompletionParser.NamelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplist([NotNull] LuaCompletionParser.ExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplist([NotNull] LuaCompletionParser.ExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] LuaCompletionParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] LuaCompletionParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixexp([NotNull] LuaCompletionParser.PrefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixexp([NotNull] LuaCompletionParser.PrefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctioncall([NotNull] LuaCompletionParser.FunctioncallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctioncall([NotNull] LuaCompletionParser.FunctioncallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrExp([NotNull] LuaCompletionParser.VarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrExp([NotNull] LuaCompletionParser.VarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] LuaCompletionParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] LuaCompletionParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarSuffix([NotNull] LuaCompletionParser.VarSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarSuffix([NotNull] LuaCompletionParser.VarSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.terminalVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminalVar([NotNull] LuaCompletionParser.TerminalVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.terminalVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminalVar([NotNull] LuaCompletionParser.TerminalVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.terminalVarSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminalVarSuffix([NotNull] LuaCompletionParser.TerminalVarSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.terminalVarSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminalVarSuffix([NotNull] LuaCompletionParser.TerminalVarSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameAndArgs([NotNull] LuaCompletionParser.NameAndArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameAndArgs([NotNull] LuaCompletionParser.NameAndArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.newExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewExp([NotNull] LuaCompletionParser.NewExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.newExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewExp([NotNull] LuaCompletionParser.NewExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.arrayAccessExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccessExp([NotNull] LuaCompletionParser.ArrayAccessExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.arrayAccessExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccessExp([NotNull] LuaCompletionParser.ArrayAccessExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] LuaCompletionParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] LuaCompletionParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctiondef([NotNull] LuaCompletionParser.FunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctiondef([NotNull] LuaCompletionParser.FunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncbody([NotNull] LuaCompletionParser.FuncbodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncbody([NotNull] LuaCompletionParser.FuncbodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParlist([NotNull] LuaCompletionParser.ParlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParlist([NotNull] LuaCompletionParser.ParlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableconstructor([NotNull] LuaCompletionParser.TableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableconstructor([NotNull] LuaCompletionParser.TableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldlist([NotNull] LuaCompletionParser.FieldlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldlist([NotNull] LuaCompletionParser.FieldlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] LuaCompletionParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] LuaCompletionParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.terminalField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminalField([NotNull] LuaCompletionParser.TerminalFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.terminalField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminalField([NotNull] LuaCompletionParser.TerminalFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldsep([NotNull] LuaCompletionParser.FieldsepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldsep([NotNull] LuaCompletionParser.FieldsepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorOr([NotNull] LuaCompletionParser.OperatorOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorOr([NotNull] LuaCompletionParser.OperatorOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAnd([NotNull] LuaCompletionParser.OperatorAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAnd([NotNull] LuaCompletionParser.OperatorAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorComparison([NotNull] LuaCompletionParser.OperatorComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorComparison([NotNull] LuaCompletionParser.OperatorComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorStrcat([NotNull] LuaCompletionParser.OperatorStrcatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorStrcat([NotNull] LuaCompletionParser.OperatorStrcatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAddSub([NotNull] LuaCompletionParser.OperatorAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAddSub([NotNull] LuaCompletionParser.OperatorAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorMulDivMod([NotNull] LuaCompletionParser.OperatorMulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorMulDivMod([NotNull] LuaCompletionParser.OperatorMulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorBitwise([NotNull] LuaCompletionParser.OperatorBitwiseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorBitwise([NotNull] LuaCompletionParser.OperatorBitwiseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorUnary([NotNull] LuaCompletionParser.OperatorUnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorUnary([NotNull] LuaCompletionParser.OperatorUnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorPower([NotNull] LuaCompletionParser.OperatorPowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorPower([NotNull] LuaCompletionParser.OperatorPowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] LuaCompletionParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] LuaCompletionParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaCompletionParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] LuaCompletionParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaCompletionParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] LuaCompletionParser.StringContext context);
}
