//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from StandardLua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="StandardLuaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IStandardLuaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChunk([NotNull] StandardLuaParser.ChunkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChunk([NotNull] StandardLuaParser.ChunkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] StandardLuaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] StandardLuaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] StandardLuaParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] StandardLuaParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetstat([NotNull] StandardLuaParser.RetstatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetstat([NotNull] StandardLuaParser.RetstatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] StandardLuaParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] StandardLuaParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncname([NotNull] StandardLuaParser.FuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncname([NotNull] StandardLuaParser.FuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarlist([NotNull] StandardLuaParser.VarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarlist([NotNull] StandardLuaParser.VarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamelist([NotNull] StandardLuaParser.NamelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamelist([NotNull] StandardLuaParser.NamelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplist([NotNull] StandardLuaParser.ExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplist([NotNull] StandardLuaParser.ExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] StandardLuaParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] StandardLuaParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixexp([NotNull] StandardLuaParser.PrefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixexp([NotNull] StandardLuaParser.PrefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctioncall([NotNull] StandardLuaParser.FunctioncallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctioncall([NotNull] StandardLuaParser.FunctioncallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrExp([NotNull] StandardLuaParser.VarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrExp([NotNull] StandardLuaParser.VarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] StandardLuaParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] StandardLuaParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarSuffix([NotNull] StandardLuaParser.VarSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarSuffix([NotNull] StandardLuaParser.VarSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameAndArgs([NotNull] StandardLuaParser.NameAndArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameAndArgs([NotNull] StandardLuaParser.NameAndArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] StandardLuaParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] StandardLuaParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctiondef([NotNull] StandardLuaParser.FunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctiondef([NotNull] StandardLuaParser.FunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncbody([NotNull] StandardLuaParser.FuncbodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncbody([NotNull] StandardLuaParser.FuncbodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParlist([NotNull] StandardLuaParser.ParlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParlist([NotNull] StandardLuaParser.ParlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableconstructor([NotNull] StandardLuaParser.TableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableconstructor([NotNull] StandardLuaParser.TableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldlist([NotNull] StandardLuaParser.FieldlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldlist([NotNull] StandardLuaParser.FieldlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] StandardLuaParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] StandardLuaParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldsep([NotNull] StandardLuaParser.FieldsepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldsep([NotNull] StandardLuaParser.FieldsepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorOr([NotNull] StandardLuaParser.OperatorOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorOr([NotNull] StandardLuaParser.OperatorOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAnd([NotNull] StandardLuaParser.OperatorAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAnd([NotNull] StandardLuaParser.OperatorAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorComparison([NotNull] StandardLuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorComparison([NotNull] StandardLuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorStrcat([NotNull] StandardLuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorStrcat([NotNull] StandardLuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAddSub([NotNull] StandardLuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAddSub([NotNull] StandardLuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorMulDivMod([NotNull] StandardLuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorMulDivMod([NotNull] StandardLuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorBitwise([NotNull] StandardLuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorBitwise([NotNull] StandardLuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorUnary([NotNull] StandardLuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorUnary([NotNull] StandardLuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorPower([NotNull] StandardLuaParser.OperatorPowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorPower([NotNull] StandardLuaParser.OperatorPowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] StandardLuaParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] StandardLuaParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StandardLuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] StandardLuaParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StandardLuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] StandardLuaParser.StringContext context);
}
