//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from StandardLua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="StandardLuaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IStandardLuaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChunk([NotNull] StandardLuaParser.ChunkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] StandardLuaParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStat([NotNull] StandardLuaParser.StatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetstat([NotNull] StandardLuaParser.RetstatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] StandardLuaParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncname([NotNull] StandardLuaParser.FuncnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarlist([NotNull] StandardLuaParser.VarlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamelist([NotNull] StandardLuaParser.NamelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplist([NotNull] StandardLuaParser.ExplistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp([NotNull] StandardLuaParser.ExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixexp([NotNull] StandardLuaParser.PrefixexpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctioncall([NotNull] StandardLuaParser.FunctioncallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarOrExp([NotNull] StandardLuaParser.VarOrExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] StandardLuaParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarSuffix([NotNull] StandardLuaParser.VarSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameAndArgs([NotNull] StandardLuaParser.NameAndArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] StandardLuaParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiondef([NotNull] StandardLuaParser.FunctiondefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncbody([NotNull] StandardLuaParser.FuncbodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParlist([NotNull] StandardLuaParser.ParlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTableconstructor([NotNull] StandardLuaParser.TableconstructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldlist([NotNull] StandardLuaParser.FieldlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] StandardLuaParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldsep([NotNull] StandardLuaParser.FieldsepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorOr([NotNull] StandardLuaParser.OperatorOrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorAnd([NotNull] StandardLuaParser.OperatorAndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorComparison([NotNull] StandardLuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorStrcat([NotNull] StandardLuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorAddSub([NotNull] StandardLuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorMulDivMod([NotNull] StandardLuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorBitwise([NotNull] StandardLuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorUnary([NotNull] StandardLuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorPower([NotNull] StandardLuaParser.OperatorPowerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] StandardLuaParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="StandardLuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] StandardLuaParser.StringContext context);
}
